### ISSUE TITLE
Library crashes when providing app-specific locale

### ISSUE THREAD

**Issue by kightsonsanom** [miguelpruivo/country_codes#1]
Hello,

I am trying to get country code based on the locale of the application, here is how I am invoking the method:

```
    final localeCodes = CountryCodes.detailsForLocale(Localizations.localeOf(context));
```

Following throws this error:

![image](https://user-images.githubusercontent.com/24854180/86898860-847ef280-c109-11ea-8441-dfee394e270a.png)

This is caused because `countryCode` is an optional parameter in Locale and might be null, here is the locale constructor:
![image](https://user-images.githubusercontent.com/24854180/86902750-ab8bf300-c10e-11ea-92d3-89cdc38415bc.png)

and here is how the locale is resolved in the library

![image](https://user-images.githubusercontent.com/24854180/86902809-c1011d00-c10e-11ea-8857-6b562f4ba562.png)

**Comment by miguelpruivo** [comment]
Hi @kightsonsanom, this is not actually a bug with the plugin itself but rather from iOS simulator that you might be using with it.

For some reason, iOS simulators don't have a default country set (this doesn't ever happen with real devices btw) and you'll need to go to settings > region > select a country even if it's already selected. After that you should be fine.

Anyway, I've updated the `assert` to also make sure that `countryCode` is not `null` and provide this same information to the developer as it may be missed at first.

Let me know if it worked for you.

Thanks!

**Comment by kightsonsanom** [comment]
Hi @miguelpruivo thank you for the quick answer. 
The issue above happened to me on an Android emulator but I also checked on physical Pixel 2 XL and OnePlus 6 and it also happens there. For some reason, `countryCode` is still null.

What about accessing CountryDetails map keys by `languageCode` instead? This property is a required one on Locale object.

**Comment by miguelpruivo** [comment]
@kightsonsanom I'm afraid that every device should have a country associated because the language tag must be from a country. This is, `en` can be a language tag from many countries, and this could result in wrong information being provided.

I'm surprised that in Android devices you are experiencing this. Might have to investigate this. At first, this was only an issue with iOS simulators.

**Comment by kightsonsanom** [comment]
I agree that the country code is necessary for this case. If you find yourself not able to reproduce the issue I can provide more details. Thanks!

**Comment by miguelpruivo** [comment]
@kightsonsanom yes, that would be great. How do you manage to replicate it consistently?

**Comment by kightsonsanom** [comment]
I am actually doing it the same way it is done in the package README :

1. Initialize the plugin:
![image](https://user-images.githubusercontent.com/24854180/86926530-7abdb500-c132-11ea-8e67-633bfce92cc1.png)

2. Use it on the first screen of the application. I use it in `didChangeDependencies` not `initState` because of `Localizations` Inherited widget, but in the `build` method the result is the same. 

![image](https://user-images.githubusercontent.com/24854180/86926658-9de86480-c132-11ea-9f75-d52b1acec03d.png)


Here I think there is a mistake in plugin Readme, `detailsForLocale` is a method defined in `CountryCodes` not `CountryDetails` class but its not that important. Also in Readme, there is `Localization` instead if `Localizations`, is that a typo too? Also Readme fragment for the reference.

![image](https://user-images.githubusercontent.com/24854180/86926841-d8520180-c132-11ea-908f-3df953227d2a.png)

**Comment by kightsonsanom** [comment]
> For some reason, iOS simulators don't have a default country set (this doesn't ever happen with real devices btw) and you'll need to go to settings > general > language & region > region > select one, even if it's already selected. After that you should be fine.

I was able to reproduce this one as well. It happens on iOS simulator when we request device-specific locale like this
` final localeCodes = CountryCodes.detailsForLocale();` 

In such case setting region in the settings solves this particular problem but it is different than than the issue of this topic.

**Comment by miguelpruivo** [comment]
Added default `Locale` to `en-US` whenever device hasn't one — although this is likely to only happen on iOS simulators.
