### ISSUE TITLE
QUESTION:  get dial code from isocountry

### ISSUE THREAD

**Issue by alexlovar** [miguelpruivo/country_codes#13]
Hello,  how i can setup a locale for an isocountry to get the respective dial code?
for example for USA or any other country
```
final CountryDetails details = CountryCodes.detailsForLocale("US");

print(details.dialCode); // Displays the dial code for US, +1.
```

thanks for your help!

**Comment by miguelpruivo** [comment]
I’m sorry I didn’t get your question. Mind to elaborate? Thank you.

**Comment by alexlovar** [comment]
thank you for your response, i have the isocountry code and i want to get the full country name, is possible to passing this isocountry to the plugin as the Locale? like:

final Locale deviceLocale="CA"

 for example something like this:
```
var IsoCountryCode="CA";
final Locale deviceLocale=IsoCountryCode;
final CountryDetails details = CountryCodes.detailsForLocale(*IsoCountryCode*);
print(details.dialCode);
print(details.name); 
```
result:
  +2
  Canada

**Comment by miguelpruivo** [comment]
I think it can be easily added, yes.

**Comment by alexlovar** [comment]
thank you so much

**Comment by miguelpruivo** [comment]
I'm sorry, but right now, after looking into the plugin's source, I can see that you should be able to do it as it is, like so:
```
Locale IsoCountryCode=Locale("en", "CA");
final CountryDetails details = CountryCodes.detailsForLocale(IsoCountryCode);
print(details.dialCode); // +1
print(details.name);  // Canada
```

**Comment by sarveshcoditron** [comment]
What if I only have ISO alpha-2 code,  I should get country details as iso code is unique for every country
