### ISSUE TITLE
List of all CountryDetails

### ISSUE THREAD

**Issue by marinkobabic** [miguelpruivo/country_codes#16]
I would like to display all the countries to the user. Once user has selected a specific country, iso code will be used. How to get CountryDetails of all languages?

**Comment by miguelpruivo** [comment]
Hi, I’m not sure I understand your use case. You want to display a list with all countries? Currently that’s not possible but I accept it as a suggestion.

**Comment by marinkobabic** [comment]
Yes. User has to select the country as first. To expose such a method would be great.

**Comment by wizlif** [comment]
Same here, ability to export [this list](https://github.com/miguelpruivo/country_codes/blob/master/lib/src/codes.dart) would be great.

**Comment by miguelpruivo** [comment]
@wizlif added the feature in a PR. I’ll publish the version asap. Thank you!
