### ISSUE TITLE
DialCodeFormatter Not Working Anymore

### ISSUE THREAD

**Issue by Flexmess** [miguelpruivo/country_codes#22]
Hi,

I wanted to use the DialCodeFormatter as shown in your example :
`TextFormField(
  keyboardType: TextInputType.phone,
  inputFormatters: [DialCodeFormatter()],
);`
But it didn't work in my project. So I tried your example by cloning the repo, but it seems it didn't work anymore because I got this screen on the device :
![image](https://user-images.githubusercontent.com/96067192/147775810-feeb5329-dec2-4421-9366-a8ed81ce7b30.png)
Any solution to resolve this ?

**Comment by miguelpruivo** [comment]
Hi, you were running the example app.
