### ISSUE TITLE
Even after increasing the minSDkVersion to 21, App does not run

### ISSUE THREAD

**Issue by ishaileshmishra** [miguelpruivo/country_codes#24]
Throwing below error. Please help me with it

Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
/Users/shaileshmishra/Desktop/currency_converter/android/app/src/debug/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [:country_codes] /Users/shaileshmishra/Desktop/currency_converter/build/country_codes/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.miguelruivo.flutter.plugin.countrycodes.country_codes" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [:country_codes] /Users/shaileshmishra/Desktop/currency_converter/build/country_codes/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 21,
  		or use tools:overrideLibrary="com.miguelruivo.flutter.plugin.countrycodes.country_codes" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Running Gradle task 'assembleDebug'...                              4.2s

The plugin country_codes requires a higher Android SDK version.
Fix this issue by adding the following to the file /Users/shaileshmishra/Desktop/currency_converter/android/app/build.gradle:
android {
  defaultConfig {
    minSdkVersion 21
  }
}

**Comment by miguelpruivo** [comment]
Shouldn't be an issue now with the namespace added.
