### ISSUE TITLE
localizedName always returns null

### ISSUE THREAD

**Issue by pelfert** [miguelpruivo/country_codes#25]
If I use the method CountryCodes.countryCodes() to receive a list of all country codes and I try to access the value of localizedName, I always get null. 

I tried it initializing CountryCodes with either default options (device locale) and also US or DE locale.
Neither of them returned a value in localizedName.

Is this already known?

**Comment by Aqua-Ye** [comment]
Fixed with https://github.com/miguelpruivo/country_codes/pull/29
