### ISSUE TITLE
Getting wrong dialCode.

### ISSUE THREAD

**Issue by panchalAlpit** [miguelpruivo/country_codes#28]
I'm getting wrong dialCode. Right now my location is India but I'm getting the US dialCode. So I need to add something else in my code or not!

![Screenshot 2022-06-14 at 11 01 35 AM](https://user-images.githubusercontent.com/48007084/173501306-8a3d8b32-84aa-4414-be12-b53a48aad8b1.png)

So what can I do for getting current country dialCode?
Thanks

**Comment by miguelpruivo** [comment]
You need to provide the country code you want in the `CountryCoides.init(locale)` where the locale is what you want. Even the `defailsForLocale()` supports a custom parameter of locale.
