### ISSUE TITLE
Alpha3Code is null

### ISSUE THREAD

**Issue by jpare-sonepar** [miguelpruivo/country_codes#36]
CountryCodes.countryCodes() return a list of CountryDetails. Alpha3Code property of CountryDetails is always null for any country. 
![Screen Shot 2024-05-13 at 14 49 48 PM](https://github.com/miguelpruivo/country_codes/assets/118768146/e80fcdcd-b3ec-4dba-8856-cce6df93d0da)

**Comment by nerder** [comment]
Seems like there is no `alpha3Code` in `codes.dart` 

Maybe @miguelpruivo can explain better.

**Comment by sauravniraula** [comment]
I have added alpha3Code and opened a pull request.

**Comment by miguelpruivo** [comment]
Merged. Closing.
