### ISSUE TITLE
getting error on build

### ISSUE THREAD

**Issue by primemb** [miguelpruivo/country_codes#4]
Hi, I got this error when I try to build package 

`A problem occurred evaluating root project 'country_codes'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in D:\programer\flutter\.pub-cache\hosted\pub.dartlang.org\country_codes-1.0.1\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip`

**Comment by miguelpruivo** [comment]
Hi @primemb! 

You just need to update your project’s gradle version to 5.4.1 or above. 

This should be inside your android/build.gradle file:
```
dependencies {
    classpath 'com.android.tools.build:gradle:5.4.1'
}
```

**Comment by primemb** [comment]
the problem was my gradle cache i remove all cache and it work now sorry and thank you for fast response
