### ISSUE TITLE
Dissolution of Netherlands Antilles

### ISSUE THREAD

**Issue by comESK** [miguelpruivo/country_codes#5]
Hello!

I was going through your codes.dart since I needed to get an up-to-date alpha 2 code and English country name Map for a project, and I noticed a couple things as I was verifying using iso.org, the biggest one being the dissolution of Netherlands Antilles in 2010, which led to the AN code being phased out in favor of BQ (Bonaire, Sint Eustatius and Saba), CW (Curaçao), and SX (Sint Maarten (Dutch part)). That last one ended up splitting the Saint Martin Island into French and Dutch parts, so that might also affect MF in that it may now have to be "Saint Martin (French part)".

I also noticed a couple of other little things:
1) I didn't see EH (Western Sahara) listed, which makes sense since that whole area is in dispute, but it is still listed on iso.org, and many people still use it under ISO 3166-2, grandfathering it over from ISO 3166-1, so I am not sure if you may want to add it in?
2) It looks like UM (United States Minor Outlying Islands) may be missing entirely, which might not be so great for people looking for an exhaustive list.
3) XK (Kosovo) is technically not yet on iso.org, even though it is a generally accepted temporary country code, so I am not sure if you would like to keep it or wait to add it back when it is official?
4) I think I caught a duplicate entry for Puerto Rico, one with its alpha 2 code misassigned to its alpha 3 code (see line 892).

Thank you for making this package--it has saved me hours of time, and I very much appreciate your hard work! I hope my feedback helps to make this already great repo even better :)

Disclaimer: I am not at all an expert in ISO codes. All my statements are based on my brief research from me trying to make sure I do this part of my project as correctly and accurately as possible.

**Comment by miguelpruivo** [comment]
@comESK feel free to add those in a PR, I'd be glad to merge and make the package more complete. I'm also no expert on ISO or whatsoever, just created the package because I actually needed and wasn't something similar at the time. 🙂

**Comment by comESK** [comment]
@miguelpruivo thanks for the quick response! I'll work on the PR later today when I am free 👍

**Comment by comESK** [comment]
@miguelpruivo done 👍
Is there anything else I need to do before closing?

**Comment by miguelpruivo** [comment]
No, that’s all. Thank you for your contribution! 👍
