### ISSUE TITLE
Module 'country_codes' not found

### ISSUE THREAD

**Issue by ravipromact2306** [miguelpruivo/country_codes#7]
While archiving from Xcode it shows this error. Can anyone help me with this?

**Comment by miguelpruivo** [comment]
Hi! Make sure you have `use_frameworks!` on your Podfile.

**Comment by ravipromact2306** [comment]
Thanks @miguelpruivo for your reply..
There is a deployment target mismatch in Runner Project and Pods.. making it similar resolves issue.

**Comment by primemb** [comment]
@ravipromact2306 can i ask how you solve it? the "use_frameworks!" not work for me

**Comment by ravipromact2306** [comment]
@primemb you can check in pod file "**platform: ios, '10.0'**" and your **project deployment target version**.. it must be different. make it the same will resolve your issue.
